#!/usr/bin/env php

<?php

$url = "https://lawguidebook.rksoftwares.fun/";
$json = json_encode([]);
$header = [
    "Content-Type: application/json"
];
$request_method = "get";

$ch = curl_init($url);

if($request_method == "post"){

    curl_setopt_array($ch, [

        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_HTTPHEADER => $header,
        CURLOPT_POSTFIELDS => $json,
        CURLOPT_CONNECTTIMEOUT => 5,
        CURLOPT_TIMEOUT => 10

    ]);

}else{

    curl_setopt_array($ch, [

        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPGET => true,
        CURLOPT_HTTPHEADER => $header,
        CURLOPT_CONNECTTIMEOUT => 5,
        CURLOPT_TIMEOUT => 10

    ]);

}

$result = curl_exec($ch);

if(curl_error($ch)){

    echo " \n";
    echo "===> Error : " . curl_error($ch);
    echo " \n";

}else{

    echo " \n";
    echo json_encode(json_decode($result, true), JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    echo " \n";

}

echo " \n";
echo "===> Status : " . curl_getinfo($ch, CURLINFO_HTTP_CODE);
echo " \n";

curl_close($ch);